apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: dhg-rateauto-dev-backend-config
  namespace: dhg-rateauto-dev-namespace
spec:
  timeoutSec: 1500
  securityPolicy:
    name: dhg-rateauto-widget-ui-pol
