apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: dhg-rateauto-dev-frontend-config
  namespace: dhg-rateauto-dev-namespace
spec:
  sslPolicy: dhg-rateauto-ssl-pol
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
